// // ================= QUESTION =================
// GET
export const ACTION_GET_QUESTIONS = 'ACTION_GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';
// GET QUESTION BY CATEGORY
export const ACTION_GET_QUESTIONS_CATEGORY = 'ACTION_GET_QUESTIONS_CATEGORY';
export const GET_QUESTIONS_CATEGORY_SUCCESS = 'GET_QUESTIONS_CATEGORY_SUCCESS';
export const GET_QUESTIONS_CATEGORY_ERROR = 'GET_QUESTIONS_CATEGORY_ERROR';
// GET QUESTION BY COURSE
export const ACTION_GET_QUESTIONS_COURSE = 'ACTION_GET_QUESTIONS_COURSE';
export const GET_QUESTIONS_COURSE_SUCCESS = 'GET_QUESTIONS_COURSE_SUCCESS';
export const GET_QUESTIONS_COURSE_ERROR = 'GET_QUESTIONS_COURSE_ERROR';
// CREATE
export const ACTION_CREATE_QUESTION = 'ACTION_CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_ERROR = 'CREATE_QUESTION_ERROR';
// UPDATE
export const ACTION_UPDATE_QUESTION = 'ACTION_UPDATE_QUESTION';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_ERROR = 'UPDATE_QUESTION_ERROR';
// DELETE
export const ACTION_DELETE_QUESTION = 'ACTION_DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';

// // ================= CATEGORY =================
// GET
export const ACTION_GET_CATEGORIES = 'ACTION_GET_CATEGORIES';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
// CREATE
export const ACTION_CREATE_CATEGORY = 'ACTION_CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
// UPDATE
export const ACTION_UPDATE_CATEGORY = 'ACTION_UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';
// DELETE
export const ACTION_DELETE_CATEGORY = 'ACTION_DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const ACTION_CREATE_LESSON = 'ACTION_CREATE_LESSON';
export const ACTION_DELETE_LESSON = 'ACTION_DELETE_LESSON';
export const ACTION_UPDATE_LESSON = 'ACTION_UPDATE_LESSON';

// // ================= UI LOADING =================
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';

// // ================= AUTH =================
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SEND_MAIL = 'SEND_MAIL';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILED = 'SEND_MAIL_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const REDIRECT_AFTER_SIGN_UP_SUCCESS = '/login';
export const REDIRECT_AFTER_LOGIN_SUCCESS = '/dashboard';

// // ================= USER =================
// GET
export const ACTION_GET_USER = 'ACTION_GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
// GET ONE
export const ACTION_GET_ONE_USER = 'ACTION_GET_ONE_USER';
export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS';
export const GET_ONE_USER_ERROR = 'GET_ONE_USER_ERROR';
// CREATE
export const ACTION_CREATE_USER = 'ACTION_CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
// UPDATE AVATAR
export const ACTION_UPDATE_AVATAR = 'ACTION_UPDATE_AVATAR';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_ERROR = 'UPDATE_AVATAR_ERROR';
// UPDATE USER PROFILE
export const ACTION_UPDATE_PROFILE = 'ACTION_UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

// // ================= COURSE =================
// GET
export const ACTION_GET_COURSE = 'ACTION_GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';
// CREATE
export const ACTION_CREATE_COURSE = 'ACTION_CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR';
// UPDATE
export const ACTION_UPDATE_COURSE = 'ACTION_UPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';
// DELETE
export const ACTION_DELETE_COURSE = 'ACTION_DELETE_COURSE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';
